### ISSUE TITLE
请问这个插件如何使用？

### ISSUE THREAD

**Issue by BiFangKNT** [kirifujinagisa/FileSender#1]
如题。我摸索了半天也没太搞懂，我太菜了，希望大大能教教我！

**Comment by BiFangKNT** [comment]
我目前知道pkg.plugin.context中的`EventContext`类没有`send_file`方法，但是我不知道该如何编写此方法

**Comment by koishi8** [comment]
> 我目前知道pkg.plugin.context中的`EventContext`类没有`send_file`方法，但是我不知道该如何编写此方法

请问问题解决了吗，我现在也遇到了这个问题

**Comment by BiFangKNT** [comment]
> > 我目前知道pkg.plugin.context中的`EventContext`类没有`send_file`方法，但是我不知道该如何编写此方法
> 
> 请问问题解决了吗，我现在也遇到了这个问题

当时我不懂，现在应该是可以独自实现这个脚本功能了，但是不想做，主要原因是这个功能没啥用，次要原因是我懒😂

**Comment by koishi8** [comment]
> > > 我目前知道pkg.plugin.context中的`EventContext`类没有`send_file`方法，但是我不知道该如何编写此方法
> > 
> > 
> > 请问问题解决了吗，我现在也遇到了这个问题
> 
> 当时我不懂，现在应该是可以独自实现这个脚本功能了，但是不想做，主要原因是这个功能没啥用，次要原因是我懒😂

好的好的，谢谢
